image: Visual Studio 2015
configuration: Release

environment:
  PYPI_USER:
    secure: 51yLKbqfXovqhV089twFAA==
  PYPI_PASS:
    secure: yYfy7feFy3c1kXFGCWnZlSV59DMe+4TT2Ko2Knzgd62/aV6QZfIkto6SdclcNIjtS+7KDWSur1MaxZIW5yStKKhIEoWHpYhbt7pfYnfIvvHhTl1doDCQzsZPmmR0j6mBNe6ml3uHPb8RyhoGDYnOYvfBHPG6MKFe1Qij2EGQ2/y7J/wZ1a9jk6blYaSoBi1jDgZRS84epK2S6wJZa3lPYgNDrukAcxv/O4WIuJJvvsIomzB8paMU4L3Zy4rUxhz9ybVep5Kd4PYxW9SJX5RSZg==

platform:
- x64
- Win32

before_build:
    - appveyor DownloadFile https://github.com/chezou/kytea/releases/download/0.4.7-3/kytea-win-%PLATFORM%.zip
    - 7z x kytea-win-%PLATFORM%.zip -okytea
    - cp -r kytea\include include
    - cp  kytea\lib\libkytea.lib lib\kytea\

build_script:
    - call .\ci\build.bat

artifacts:
  - path: 'dist\*.whl'
    name: kytea-win

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        py -3 -m pip install twine
        py -3 -m twine upload -u ${Env:PYPI_USER} -p ${Env:PYPI_PASS} --skip-existing dist/*.whl
      } else {
        Write-Output "No tag for deployment"
      }
